version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        command: sudo apt update && sudo apt install git -y && git --version

      # Update environment
      - run: sudo apt update

      # Install rsync. It will be used to upload our code to server
      - run: sudo apt-get install rsync

      # Sync the SSH keys 
      - add_ssh_keys

      # Check out the code in the project directory
      - checkout

      # Install JS dependencies.
      # Of course, you may not need this. It just shows how to use some commands such as npm
      - run: npm install

      # Run your command
      - run: npm run build

      # Run your command
      - run: npm run test

      # Add the server to known hosts
      - run: ssh-keyscan -H 45.32.118.249 >> ~/.ssh/known_hosts

      # Upload your files to server.
      - run: rsync -avce ssh --exclude 'node_modules' --exclude 'dist/*' ./ root@45.32.118.249:~/public_server/

      # 
      - run: ssh -o "StrictHostKeyChecking no" root@45.32.118.249 "cd ~/public_server/; npm install;"